steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/project-317606fd-894f-479f-aeb/my-app:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/project-317606fd-894f-479f-aeb/my-app:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'my-service',
        '--image', 'gcr.io/project-317606fd-894f-479f-aeb/my-app:$SHORT_SHA',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/project-317606fd-894f-479f-aeb/my-app:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
